- name: Run Ansible Playbook
  uses: dawidd6/action-ansible-playbook@v2
  with:
    playbook: ansible/playbook.yml
    inventory: ansible/inventory.ini
    key: ${{ secrets.EC2_SSH_KEY }}
  env:
    ANSIBLE_HOST_KEY_CHECKING: "False"